author: Tạ Minh Luận

keywords: Hexo, Theme-AD

description: 董沅鑫的小站

# 导航栏头部名称
nav_name: LuanTM

# 导航栏座右铭
motto: "Nếu cuộc đời này đáng sống thì cũng đáng để ghi lại"

github: "https://github.com/taminhluan/"

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss: 

# 自定义样式文件
custom_styles: 

# 自定义脚本文件
custom_scripts: 

# 代码高亮主题: normal | night | night blue | night bright | night eighties
highlight_theme: "night eighties"

# 开启数学公式渲染
mathjax: true

copyright:
  enable: true
  author: "Tạ Minh Luận"
  show_link: true
  more: '
Copyright Notice: All articles in this blog use <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> unless otherwise stated. License Agreement. Please indicate the source!'

# 建站时间. 格式：YYYY-MM-DD
start_time: "2019-06-26"

# 如何开启 评论&统计 插件：https://taminhluan.github.io/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: Hyq9wkH495DgNHWhDQCOfQSp-gzGzoHsz # 填写您的appid
  appkey: WaR7nrzhliHj9aVwdQzkdlGd # 填写您的appkey
  comment: true # 是否开启评论系统
  count: true # 是否开启文章统计

# 需要保证leancloud.count为true
welcome: 
  enable: false
  interval: 30

# 需要保证leancloud.comment为false
disqus: 
  enable: false
  id: 

# 需要保证leancloud.count为false
busuanzi: false

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
# passwords: 
#   - efe07af7441da2b69c4a41e42e73be4db47f66010a56900788a458354a7373ec # godbmw

share:
  twitter: true
  facebook: true
  weibo: false
  qq: false
  wechat: false

analytics:
  baidu:
    enable: false
  google:
    enable: false
    id: 
  "360":
    enable: false
    id: 

# 打赏图片
reward:
  -
    src: /images/wechat.png
    alt: "WeChat"
  -
    src: /images/alipay.png
    alt: "AliPay"

# 第三方库的CDN地址
# 请根据情况自行决定是否替换为国内CDN
cdn: 
  leancloud: "//cdn.jsdelivr.net/npm/leancloud-storage@3.11.1/dist/av-min.js"
  mathjax: "//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
  valine: "//unpkg.com/valine/dist/Valine.min.js"
  busuanzi: "//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"
  font_awesome: "//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"

nav:
  -
    name: "Home"
    path: "/"
  -
    name: "Archives"
    path: "/archives/"
  -
    name: "Tags"
    path: "/tags/"
  -
    name: "Categories"
    path: "/categories/"
  -
    name: "Friends"
    path: "/friends/"
  -
    name: "About"
    path: "/about/"

footer:
  - 
    title: "Giới thiệu"
    children:
      - 
        name: "Blog"
        path: "https://taminhluan.github.io/"
      - 
        name: "Facebook"
        path: "https://www.facebook.com/luantm96"
  -
    title: "Series tutorial"
    children:
      -
        name: "Chuyển văn bản thành giọng nói"
        path: "https://viblo.asia/s/text-to-speech-chuyen-van-ban-thanh-giong-noi-375z09nRZGW"
      -
        name: "Deeplearning cho chatbot"
        path: "https://viblo.asia/s/deep-learning-for-chatbot-RNZqg7mM50n"
 
footer_contact: "Email: luantm96@gmail.com"

friends_avatar_cdn: 
friends:
  -
    nickname: GodBMW
    avatar: /images/friends/godbmw.jpeg
    site: https://taminhluan.github.io/
    meta: Author
    show: true